trigger:
- main   # change branch if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'dockerhub-service-connection'   # service connection name in Azure DevOps
  imageName: 'yourdockerhubusername/react-app'        # DockerHub repo name

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Docker login
- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

# Step 3: Build & push image
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageName)
    dockerfile: Dockerfile               # if React app is in root
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest
